export const GET_USER_ROLES = "GET_USER_ROLES";
export const USER_ROLES_RECEIVED = 'USER_ROLES_RECEIVED';
export const USER_ROLES_REQUEST_FAILED = 'USER_ROLES_REQUEST_FAILED';

export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';
export const SUBSCRIBER_RECEIVED = 'SUBSCRIBER_RECEIVED';
export const SUBSCRIBER_REQUEST_FAILED = 'SUBSCRIBER_REQUEST_FAILED';
