export const GET_USER_ROLES = 'GET_USER_ROLES';
export const USER_ROLES_RECEIVED = 'USER_ROLES_RECEIVED';
export const USER_ROLES_REQUEST_FAILED = 'USER_ROLES_REQUEST_FAILED';

export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';
export const SUBSCRIBER_RECEIVED = 'SUBSCRIBER_RECEIVED';
export const SUBSCRIBER_REQUEST_FAILED = 'SUBSCRIBER_REQUEST_FAILED';

export const UPDATE_SUBSCRIBER = 'UPDATE_SUBSCRIBER';
export const UPDATE_SUBSCRIBER_SUCCESS = 'UPDATE_SUBSCRIBER_SUCCESS';
export const UPDATE_SUBSCRIBER_FAILED = 'UPDATE_SUBSCRIBER_FAILED';

export const CREATE_SUBSCRIBER = 'CREATE_SUBSCRIBER';
export const CREATE_SUBSCRIBER_SUCCESS = 'CREATE_SUBSCRIBER_SUCCESS';
export const CREATE_SUBSCRIBER_FAILED = 'CREATE_SUBSCRIBER_FAILED';

export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';
export const DELETE_SUBSCRIBER_SUCCESS = 'DELETE_SUBSCRIBER_SUCCESS';
export const DELETE_SUBSCRIBER_FAILED = 'DELETE_SUBSCRIBER_FAILED';

export const GET_BILLING_ACCOUNT = 'GET_BILLING_ACCOUNT';
export const BILLING_ACCOUNT_RECEIVED = 'BILLING_ACCOUNT_RECEIVED';
export const BILLING_ACCOUNT_REQUEST_FAILED = 'BILLING_ACCOUNT_REQUEST_FAILED';

export const UPDATE_BILLING_ACCOUNT = 'UPDATE_BILLING_ACCOUNT';
export const UPDATE_BILLING_ACCOUNT_SUCCESS = 'UPDATE_BILLING_ACCOUNT_SUCCESS';
export const UPDATE_BILLING_ACCOUNT_FAILED = 'UPDATE_BILLING_ACCOUNT_FAILED';

export const CREATE_BILLING_ACCOUNT = 'CREATE_BILLING_ACCOUNT';
export const CREATE_BILLING_ACCOUNT_SUCCESS = 'CREATE_BILLING_ACCOUNT_SUCCESS';
export const CREATE_BILLING_ACCOUNT_FAILED = 'CREATE_BILLING_ACCOUNT_FAILED';

export const DELETE_BILLING_ACCOUNT = 'DELETE_BILLING_ACCOUNT';
export const DELETE_BILLING_ACCOUNT_SUCCESS = 'DELETE_BILLING_ACCOUNT_SUCCESS';
export const DELETE_BILLING_ACCOUNT_FAILED = 'DELETE_BILLING_ACCOUNT_FAILED';

export const GET_SUB_BILLING_ACCOUNT = 'GET_SUB_BILLING_ACCOUNT';
export const SUB_BILLING_ACCOUNT_RECEIVED = 'SUB_BILLING_ACCOUNT_RECEIVED';
export const SUB_BILLING_ACCOUNT_REQUEST_FAILED = 'SUB_BILLING_ACCOUNT_REQUEST_FAILED';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CUSTOMER_RECEIVED = 'CUSTOMER_RECEIVED';
export const CUSTOMER_REQUEST_FAILED = 'CUSTOMER_REQUEST_FAILED';

export const UPDATE_CUSTOMER = 'UPDATE_BILLING_ACCOUNT';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_BILLING_ACCOUNT_SUCCESS';
export const UPDATE_CUSTOMER_FAILED = 'UPDATE_BILLING_ACCOUNT_FAILED';

export const CREATE_CUSTOMER = 'CREATE_BILLING_ACCOUNT';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_BILLING_ACCOUNT_SUCCESS';
export const CREATE_CUSTOMER_FAILED = 'CREATE_BILLING_ACCOUNT_FAILED';

export const DELETE_CUSTOMER = 'DELETE_BILLING_ACCOUNT';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_BILLING_ACCOUNT_SUCCESS';
export const DELETE_CUSTOMER_FAILED = 'DELETE_BILLING_ACCOUNT_FAILED';

export const GET_SUB_CUSTOMER = 'GET_SUB_CUSTOMER';
export const SUB_CUSTOMER_RECEIVED = 'SUB_CUSTOMER_RECEIVED';
export const SUB_CUSTOMER_REQUEST_FAILED = 'SUB_CUSTOMER_REQUEST_FAILED';
