const subscriptionTypes = {
  GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
  GET_SUBSCRIPTIONS_SUCCESS: 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_FAILED: 'GET_SUBSCRIPTIONS_FAILED',
  ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
  ADD_SUBSCRIPTION_SUCCESS: 'ADD_SUBSCRIPTION_SUCCESS',
  ADD_SUBSCRIPTION_FAILED: 'ADD_SUBSCRIPTION_FAILED',
  DELETE_SUBSCRIPTION: 'DELETE_SUBSCRIPTION',
  DELETE_SUBSCRIPTION_SUCCESS: 'DELETE_SUBSCRIPTION_SUCCESS',
  DELETE_SUBSCRIPTION_FAILED: 'DELETE_SUBSCRIPTION_FAILED',
};

export default subscriptionTypes;
